name: cats_tinder
description: A Flutter app that displays random cat images and breed info.
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  cached_network_image: ^3.2.0
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  intl: ^0.18.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons:

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
#  adaptive_icon_background: "#ffffff"
#  image_path: "assets/icon.png"
  image_path_android: "assets/icon.png"
  image_path_ios: "assets/icon.png"
